#pragma once
#include <mysql.h>
#include <ncurses.h>
#include <stdlib.h>
#include <algorithm>
#include <cassert>
#include <cstring>
#include <iostream>
#include <map>
#include <regex>
#include <string>
#include <utility>
#include <vector>
